#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

for ((a=1; a <=100; a++))
do
	if (( "$a % 3 == 0 && $a % 5 == 0" ))
	then
		echo "Fizz Buzz"
	elif (( "$a % 3 == 0" ))
	then
		echo "Fizz"
	elif (( "$a % 5 == 0" ))
	then
		echo "Buzz"
	else
		echo "$a"
	fi
done
