#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

while IFS=: read -r USERNAME PASSWORD USERID GROUPID USERIDINFO HOMEDIRECTORY COMMAND
do
	echo "The user $USERNAME is part of the $GROUPID gang, lives in $HOMEDIRECTORY and rides $COMMAND. $USERID's place is protected by the passcode $PASSWORD, more info about the user here: $USERIDINFO"
done </etc/passwd
